import express from "express"
import dotenv from "dotenv"
import mongoose from "mongoose"
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

import sheetService from './services/sheetService.js';

dotenv.config()
const app = express()
const PORT = process.env.PORT || 3001
const MONGOURL = process.env.MONGO_URL

//connect to mongo
mongoose.connect(MONGOURL).then(()=>{
    console.log('db is connected')
})
mongoose.connection.on("connected", () => {
    console.log("Connected to DB:", mongoose.connection.db.databaseName);
  });

app.get('/',(req,res) =>{
    res.send('hello world')
})

const dataSchema = new mongoose.Schema({
    name: String
}, { strict: false })
const dataModel = mongoose.model("testdatas", dataSchema)
app.get("/getData", async (req, res) => {
    try {
      const data = await dataModel.find();
      res.json(data); 
    } catch (err) {
      console.error("Error fetching data:", err.message);
      res.status(500).json({ error: "Failed to fetch data" });
    }
});


//connect  ggsheet
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});
//1VYW8_6TAcgJDNB9428ucVtIUn-now0r-5Gnr816wDRo //okr
//10eGgVDsvfd_T0zRCZRwOPlXC2bLZ_scHQex1-IMuBdg //okr2
const doc = new GoogleSpreadsheet('10eGgVDsvfd_T0zRCZRwOPlXC2bLZ_scHQex1-IMuBdg', serviceAccountAuth);

// console.log("First 5 rows:");
// rows.forEach((row, index) => {
//       console.log(`Row ${index + 1}:`, row._rawData); // _rawData contains an array of cell values
//     });

(async () =>{
const data = await sheetService.getSheetData(doc); // Use the function from the service
console.log(data);})()

app.listen(PORT,()=>{
  console.log('server is running on PORT:'+PORT)
})